[2023-04-10 11:48:03,253] {processor.py:163} INFO - Started process (PID=3111) to work on /opt/airflow/dags/HelloWorld.py
[2023-04-10 11:48:03,254] {processor.py:620} INFO - Processing file /opt/airflow/dags/HelloWorld.py for tasks to queue
[2023-04-10 11:48:03,254] {logging_mixin.py:109} INFO - [2023-04-10 11:48:03,254] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/HelloWorld.py
[2023-04-10 11:48:03,264] {logging_mixin.py:109} INFO - [2023-04-10 11:48:03,263] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/HelloWorld.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/HelloWorld.py", line 10, in <module>
    schedule = '0 2 * * *')
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2023-04-10 11:48:03,278] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/HelloWorld.py
[2023-04-10 11:48:03,284] {processor.py:171} INFO - Processing /opt/airflow/dags/HelloWorld.py took 0.034 seconds
